[package]
name = "jute-tui"
repository = "https://github.com/sidx04/jute"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
serde_json = "1.0.140"


[profile.release]
opt-level = 3
opt-size = "s"
codegen-units = 1
