name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir dist
          cp target/release/jute-tui dist/
          cp README.md dist/
          tar -czvf jute-tui-${{ github.ref_name }}-x86_64-linux.tar.gz -C dist .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: jute-tui-${{ github.ref_name }}-x86_64-linux.tar.gz
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
