name: Build and Upload Artifact

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Package binary
        run: |
          mkdir dist
          cp target/release/jute-tui dist/
          cp README.md dist/
          tar -czvf jute-tui-${{ github.ref_name }}-x86_64-linux.tar.gz -C dist .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jute-tui-${{ github.ref_name }}-binary
          path: jute-tui-${{ github.ref_name }}-x86_64-linux.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: jute-tui-${{ github.ref_name }}-binary

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          files: |
            jute-tui-${{ github.ref_name }}-x86_64-linux.tar.gz
